spring:
  profiles: supplier
  cloud:
    azure:
      servicebus:
        connection-string: ${CONN_STRING:default}
      retry:
        timeout: 5
        max-attempts: 3
        backoff:
          delay: 10
          multiplier: 2
    stream:
      function:
        definition: supply
      bindings:
        supply-out-0:
          destination: ${TOPIC:topic}
          group: ${SUBSCRIPTION:sub}
server:
  port: 8080          

---  
spring:
  profiles: consumer
  cloud:
    azure:
      servicebus:
        connection-string: ${CONN_STRING:default}
      retry:
        timeout: 5
        max-attempts: 3
        backoff:
          delay: 10
          multiplier: 2
    stream:
      function:
        definition: consume
      bindings:
        consume-in-0:
          destination: ${TOPIC:topic}
          group: ${SUBSCRIPTION:sub}
      servicebus:
        topic:
          bindings:
            consume-in-0:
              consumer:
                checkpoint-mode: MANUAL
      poller:
        fixed-delay: 1000
        initial-delay: 0
server:
  port: 8081